version: '3.8'

services:
 mysqldb:
   image: mysql:8.0.32
   restart: unless-stopped
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$DB_PASS
     - MYSQL_DATABASE=$DB_NAME
   ports:
     - $DB_PORT:$DB_PORT
   volumes:
     - db:/var/lib/mysql
 app:
   depends_on:
     - mysqldb
   build:
      context: .
      dockerfile: ./Dockerfile
   restart: unless-stopped
   env_file: ./.env
   ports:
     - $PORT:$PORT
   environment:
     - DB_HOST=mysqldb
     - DB_USER=$DB_USER
     - DB_PASSWORD=$DB_PASS
     - DB_NAME=$DB_NAME
     - DB_PORT=$DB_PORT
   stdin_open: true
   tty: true

volumes: 
 db: