version: "3.3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db:/data/db

  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - server
    networks:
      - app-network 
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
    depends_on:
       - webserver      
    command: certonly --webroot -w /var/www/certbot --force-renewal --email nguyencongtoana1nhvt@gmail.com -d be.uptech.com --agree-tos

volumes:
  db:

networks:
  app-network:
    driver: bridge
